ci: debug list directories

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -67,6 +67,14 @@ jobs:
       - name: Create Build Environment
         run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/2-configure.sh '-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake'
 
+      - name: List files for debug
+        run: |
+          set -ex
+          ls -l
+          ls -l ./*
+      - name: List vcpkg_installed for debug
+        run: ls -l vcpkg_installed || echo "Not found"
+
       - name: Build Server
         run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/3-build.sh
 
@@ -81,6 +89,13 @@ jobs:
         with:
           name: debuginfo.${{ matrix.distro }}.${{ matrix.version }}.x86_64
           path: ./bin/BeamMP-Server.debug
+      - name: List files for debug
+        run: |
+          set -ex
+          ls -l
+          ls -l ./*
+      - name: List vcpkg_installed for debug
+        run: ls -l vcpkg_installed || echo "Not found"
 
       - name: Build Tests
         run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/3-build-tests.sh
@@ -142,6 +157,13 @@ jobs:
 
       - name: Create Build Environment
         run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/2-configure.sh '-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake'
+      - name: List files for debug
+        run: |
+          set -ex
+          ls -l
+          ls -l ./*
+      - name: List vcpkg_installed for debug
+        run: ls -l vcpkg_installed || echo "Not found"
 
       - name: Build Server
         run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/3-build.sh
@@ -166,3 +188,10 @@ jobs:
 
       - name: Test
         run: ./bin/BeamMP-Server-tests
+      - name: List files for debug
+        run: |
+          set -ex
+          ls -l
+          ls -l ./*
+      - name: List vcpkg_installed for debug
+        run: ls -l vcpkg_installed || echo "Not found"
